Resources:
  audioUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.audioUploadBucket}
#      AccessControl: PublicRead
  resumeUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.resumeUploadBucket}
  #      AccessControl: PublicRead
  CandidatesDynamoTable:    # Logical Id of the resource
    Type: AWS::DynamoDB::Table

    Properties:
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        -
          AttributeName: "sk"
          AttributeType: "S"

      KeySchema:
          - AttributeName: "pk"
            KeyType: "HASH"
          - AttributeName: "sk"
            KeyType: "RANGE"

      TableName: ${self:custom.tableName}
      ProvisionedThroughput: # Optional, can be skipped
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5