Resources:
  CandidatesDynamoTable:    # Logical Id of the resource
    Type: AWS::DynamoDB::Table

    Properties:
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        -
          AttributeName: "sk"
          AttributeType: "S"

      KeySchema:
          - AttributeName: "pk"
            KeyType: "HASH"
          - AttributeName: "sk"
            KeyType: "RANGE"

      TableName: "Candidates"
      ProvisionedThroughput: # Optional, can be skipped
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5